name: Check Markdown links

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-link-check:
    name: Check Markdown links
    uses: ./.github/workflows/wf_mdlink.yml
    secrets: inherit
